apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      type: apigateway-nginx
  template:
    metadata:
      labels:
        type: apigateway-nginx
    spec:
      imagePullSecrets:
        - name: dockercfg
      volumes:
      - name: ssl-certificates
        secret:
          secretName: {secret_name}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: function
                operator: NotIn
                values:
                - system
      containers:
      - name: apigateway-nginx
        image: {repository}/nginx-ssl-server-certificate:{nginx_ssl_version}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: ssl-certificates
          mountPath: /secrets
          readOnly: true
        resources:
          requests:
            cpu: "1m"
        readinessProbe:
          httpGet:
            path: {health_check_url}
            port: 80
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: SERVER_NAME
          value: "{server_name}"
        - name: ROOT_REDIRECT_URL
          value: "{root_redirect_url}"
